version: "2"

services:
  php:
    container_name: php-zce-app
    build: ./docker/php
    # image: php:7.1.0-fpm-alpine
    volumes:
      - ./app:/app

  web:
    container_name: php-zce-web
    image: "nginx:1.13.8-alpine"
    volumes:
      - ./app:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    links:
      - "php"
